name: Test Project

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Deploy to Render
      uses: bounceapp/render-action@0.6.0
      with:
        service-id: ${{ secrets.SERVICE_KEY }}
